dms/urls.py
from django.urls import path, include
from . import views
from .views import send_memo_to_dms

urlpatterns = [
    path('', views.index, name='index'),
    path('document/create/', views.document_create, name='document_create'),
    path('document/<int:pk>/details/', views.document_details, name='document_details'),
    path('document/<int:pk>/update/', views.document_update, name='document_update'),
    path('document/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('search/', views.search_results, name='search'),
    path('dms/document/<int:document_id>/share/', views.share_document, name='share_document'),
    path('send_memo/<int:memo_id>/', send_memo_to_dms, name='send_memo_to_dms'),
    path('list_in_dms/', views.list_in_dms, name='list_in_dms'),
    path('count_memos_sent_to_dms/', views.count_memos_sent_to_dms, name='count_memos_sent_to_dms'),
]

projectx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user import views

from django.views.generic import TemplateView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter

app_name = 'organogram'

router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('dms/', include('dms.urls'), name='dms'),
    path('organogram/', include('organogram.urls'), name='org'),
    path('memotracker/', include('memotracker.urls'), name='memotracker'),
    path('user/', include('user.urls'), name='user'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('notification/', include('notification.urls'), name='notify'),
    path("firebase-messaging-sw.js", TemplateView.as_view(
        template_name="firebase-messaging-sw.js",
        content_type="application/javascript"
    ), name="firebase-messaging-sw.js"),
    path('api/', include(router.urls)),
    #################################### Memo to DMS
    path('memo/', include(('memotracker.urls', 'memotracker'), namespace='memotracker')),
    path('dms/', include(('dms.urls', 'dms'), namespace='dms')),
    ####################################
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from .views import CustomPasswordChangeView
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import CustomLoginView
from .views import CustomResetPasswordView
from .views import forgot_pin, reset_pin


urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/user/login/'), name='logout'),
    #path('password_change/', auth_views.PasswordChangeView.as_view(template_name='user/password_change.html'), name='password_change'),
    path('password_change/', CustomPasswordChangeView.as_view(template_name='user/password_change.html'), name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('dashboard_config/', views.dashboard_config, name='dashboard_config'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_reset/', CustomResetPasswordView.as_view(), name='password_reset'),
    path('accept_pin/', views.accept_pin, name='accept_pin'),
    path('forgot_pin/', views.forgot_pin, name='forgot_pin'),
    path('reset_pin/<str:username>/', views.reset_pin, name='reset_pin'),

    # Other URL patterns
]

organogram/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django import forms
from projectx import settings


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class BusinessUnit(models.Model):
    code = models.CharField(max_length=10)
    name_am = models.CharField(verbose_name='Name(am)', max_length=200)
    name_en = models.CharField(verbose_name='Name(en)', max_length=200)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='children')
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    bu_signature = models.ImageField(upload_to='digital_signature/', blank=True, null=True)
    location = models.CharField(max_length=150)
    contact = models.CharField(max_length=100)
    last_memo_ref_number = models.IntegerField(default=0)
    # New fields for headers and footers
    internal_header_image = models.ImageField(upload_to='headers/internal/', blank=True, null=True)
    external_header_image = models.ImageField(upload_to='headers/external/', blank=True, null=True)
    internal_footer_image = models.ImageField(upload_to='footers/internal/', blank=True, null=True)
    external_footer_image = models.ImageField(upload_to='footers/external/', blank=True, null=True)
    class Meta:
        ordering = ['name_en']

    def __str__(self):
        return f"{self.code} - {self.name_en}"

class Role(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    is_manager = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
class UserRole(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    business_unit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField()
    deligated = models.BooleanField()

    def __str__(self):
        return self.user.username + ' - ' + self.role.name + ' - ' + self.business_unit.code

class ExternalCustomer(models.Model):
    name_am = models.CharField(verbose_name='Name(am)', max_length=200)
    name_en = models.CharField(verbose_name='Name(en)', max_length=200)
    description = models.CharField(max_length=300, blank=True, null=True)
    contact = models.CharField(max_length=100, blank=True, null=True)
    customer_type = models.CharField(choices = [
        ('Org', 'Organization'),
        ('Ind', 'Individual'),
    ])

    class Meta:
        ordering = ['name_en']

    def __str__(self):
        return self.name_en + ' - ' + self.name_am

CUSTOM_DISPLAY_NAMES = {
    'user': 'Personal',
    'businessunit': 'Business Unit',
    'externalcustomer': 'External',
}

class CustomModelNameChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        model_name = obj.model.lower()
        return CUSTOM_DISPLAY_NAMES.get(model_name, obj.model)

class ContentTypeModelField(models.ForeignKey):
    def formfield(self, **kwargs):
        defaults = {
            'form_class': CustomModelNameChoiceField,
            'queryset': ContentType.objects.filter(
                models.Q(app_label='auth', model='user') |
                models.Q(app_label='organogram', model='businessunit') |
                models.Q(app_label='organogram', model='externalcustomer')
            )
        }
        defaults.update(kwargs)
        return super().formfield(**defaults)

class PermissionParent(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
class Permission(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=100, blank=True)
    display_name = models.CharField(max_length=50)
    icon = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    parent = models.ForeignKey(PermissionParent,blank=True, null=True, on_delete=models.SET_NULL)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.display_name


class RolePermission(models.Model):
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    permission = models.ForeignKey(Permission, on_delete=models.CASCADE)

    class Meta:
        ordering = ['permission__order']
    def __str__(self):
        return self.role.name + ' - ' + self.permission.name
class Profile(models.Model):
    SECURITY_QUESTIONS = [
        ("Your birth year", "Your birth year"),
        ("Your grandmother's name", "Your grandmother's name"),
        ("Name of your elementary school", "Name of your elementary school"),
        ("Your favorite color", "Your favorite color"),
        ("Your first pet's name", "Your first pet's name"),
        ("City where you were born", "City where you were born"),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=150, blank=True)
    full_name_am = models.CharField(max_length=150, blank=True) ########
    pin_code = models.CharField(max_length=128, null=True)
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to=settings.DOCUMENT_PATH)
    password_set = models.BooleanField(default=False)
    preference = models.JSONField(default=dict)
    security_question_1 = models.CharField(max_length=100, choices=SECURITY_QUESTIONS, default="Your birth year")
    security_answer_1 = models.CharField(max_length=100, null=True, blank=True)
    security_question_2 = models.CharField(max_length=100, choices=SECURITY_QUESTIONS, null=True, blank=True,
                                               default="Your grandmother's name")
    security_answer_2 = models.CharField(max_length=100, null=True, blank=True)
    security_question_3 = models.CharField(max_length=100, choices=SECURITY_QUESTIONS, null=True, blank=True,
                                               default="Name of your elementary school")
    security_answer_3 = models.CharField(max_length=100, null=True, blank=True)
    last_personal_memo_ref_number = models.IntegerField(default=0)

    # Add more fields as per your requirements

    def __str__(self):
        return self.user.username

user/forms.py
from django import forms
from django.contrib.auth.models import User
from organogram.models import Profile
from django.contrib.auth.forms import PasswordChangeForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('username', 'email')
#
# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ('bio', 'profile_picture')
#         exclude = ('birth_date', 'user')
#         labels = {
#             'bio': 'Bio',
#             'profile_picture': 'Profile',
#         }
#     def __init__(self, *args, **kwargs):
#         super(ProfileForm, self).__init__(*args, **kwargs)
#         self.fields['bio'].widget.attrs.update({'rows': 6, 'cols': 40})  # Set the size of the textarea

################################
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'profile_picture', 'full_name_am')  # Include Amharic name field
        exclude = ('birth_date', 'user')
        labels = {
            'bio': 'Bio (English)',
            'profile_picture': 'Profile Picture',
            'full_name_am': 'Full Name (Amharic)',
        }

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['bio'].widget.attrs.update({'rows': 6, 'cols': 40})  # Set size for English bio

####################
class CustomPasswordChangeForm(PasswordChangeForm):
    def clean_new_password1(self):
        password1 = self.cleaned_data.get('new_password1')
        if len(password1) < 8:
            raise ValidationError(_("Your password must contain at least 8 characters."), code='password_too_short')
        if password1.isdigit():
            raise ValidationError(_("Your password can’t be entirely numeric."), code='password_entirely_numeric')
        return password1

user/templates/user/password_change.html
{% extends 'base.html' %}

{% block contentIcon %}
    bi-person-badge
{% endblock %}

{% block contentTitle %}
    Password, PIN & SQ Settings
{% endblock %}
{% block content %}
<!-- JavaScript to dynamically add modal content -->
<script>
    // Create modal content
    var modalContent = `
    <div id="password-change-modal" class="modal" style="{% if not modal_open %}display: none;{% endif %}">
    <div class="modal-content">
        <h4 style="margin-top: 5px; margin-bottom: 15px;">Default Password Change & set PIN & Security Questions!</h4>

        <!-- Display form errors -->
        {% if form.errors %}
        <div class="errorlist">
            <ul>
                {% for field, errors in form.errors.items %}
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        <!-- Form fields -->
        <form id="password-change-form" method="post">
            {% csrf_token %}
            <div class="row">
                <!-- Left column -->
                <div class="col-md-6">
                    <!-- Full Name -->
                    <div class="form-group">

                        <input type="text" class="form-control" id="id_full_name" name="full_name" placeholder="User Name" required>
                    </div>
                    <!-- Old password -->
                    <div class="form-group">

                        <input type="password" class="form-control" id="id_old_password" name="old_password" placeholder="Old Password" required>
                    </div>

                    <!-- New password -->
                    <div class="form-group">

                        <input type="password" class="form-control" id="id_new_password1" name="new_password1" placeholder="New Password" required>
                    </div>

                    <!-- New password confirmation -->
                    <div class="form-group">

                        <input type="password" class="form-control" id="id_new_password2" name="new_password2" placeholder="Confirm New Password" required>
                    </div>

                    <!-- PIN Code -->
                    <div class="form-group pin-container">
                        <label for="pin_code">PIN Code:<span style="color: red;"> * </span></label>
                        <input type="password" placeholder="____"
                            onkeypress="return restrictToInteger(event, 'pwdPinError')"
                            title="Please enter a valid integer (0-9)"
                            class="form-control text-center fs-4"
                            style="letter-spacing: 2em;"
                            id="pin_code" name="pin_code" maxlength="4" required>
                        <i id="pwd-change-modal" class="pin-toggle pin-toggle-pwdX bi bi-eye-fill" onclick="togglePasswordVisibility('pin_code', 'pwd-change-modal')"></i>
                        <div id="pwdPinError" class="invalid-feedback my-2 text-danger">Please enter a valid integer (0-9).</div>
                    </div>
                </div>

                <!-- Right column -->
                <div class="col-md-6">

                    <!-- Security questions -->
                    <div class="form-group">

                        <select class="form-control" id="id_security_question_1" name="security_question_1" required>
                            <option value="" disabled selected>Select a security question 1</option>
                            <option value="Your birth year">Your birth year</option>
                            <option value="Your grandmother's name">Your grandmother's name</option>
                            <option value="Name of your elementary school">Name of your elementary school</option>
                            <option value="Your favorite color">Your favorite color</option>
                            <option value="Your first pet's name">Your first pet's name</option>
                            <option value="City where you were born">City where you were born</option>
                        </select>
                        <input type="text" class="form-control" id="id_security_answer_1" name="security_answer_1" placeholder="Answer" required>
                    </div>

                    <div class="form-group">

                        <select class="form-control" id="id_security_question_2" name="security_question_2" required>
                            <option value="" disabled selected>Select a security question 2</option>
                            <option value="Your birth year">Your birth year</option>
                            <option value="Your grandmother's name">Your grandmother's name</option>
                            <option value="Name of your elementary school">Name of your elementary school</option>
                            <option value="Your favorite color">Your favorite color</option>
                            <option value="Your first pet's name">Your first pet's name</option>
                            <option value="City where you were born">City where you were born</option>
                        </select>
                        <input type="text" class="form-control" id="id_security_answer_2" name="security_answer_2" placeholder="Answer" required>
                    </div>

                    <div class="form-group">

                        <select class="form-control" id="id_security_question_3" name="security_question_3" required>
                            <option value="" disabled selected>Select a security question 3</option>
                            <option value="Your birth year">Your birth year</option>
                            <option value="Your grandmother's name">Your grandmother's name</option>
                            <option value="Name of your elementary school">Name of your elementary school</option>
                            <option value="Your favorite color">Your favorite color</option>
                            <option value="Your first pet's name">Your first pet's name</option>
                            <option value="City where you were born">City where you were born</option>
                        </select>
                        <input type="text" class="form-control" id="id_security_answer_3" name="security_answer_3" placeholder="Answer" required>
                    </div>
                </div>
            </div>

            <!-- Submit button -->
            <div style="margin-top: 10px; display: flex; justify-content: center; gap: 10px;">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'login' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
    </div>`;

    // Add modal content to the body
    document.body.insertAdjacentHTML('beforeend', modalContent);

    // Get the modal
    var modal = document.getElementById("password-change-modal");

    // Show the modal when the page loads
    window.onload = function() {
        modal.style.display = "block";
    };

    // Get the <span> element that closes the modal
    var span = document.querySelector("#password-change-modal .close");

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    };

    // Prevent form submission when clicking outside the modal
    document.getElementById("password-change-form").addEventListener("submit", function(event) {
        // Prevent default form submission
        event.preventDefault();

        // Process form submission here

        // Close the modal after processing the form
        modal.style.display = "none";
    });

    // Disable closing the modal when clicking outside of it
    modal.addEventListener("click", function(event) {
        event.preventDefault();
        if (event.target === modal) {
            modal.style.display = "block";
        }
    });

    // Prevent navigation using the browser's back button
    window.addEventListener('popstate', function(event) {
        event.preventDefault();
        history.pushState(null, document.title, location.href);
    });
</script>

<style>
    /* The Modal (background) */
    .modal {
    display: none;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: transparent;
    }

    .modal-content {
        background-color: #fefefe;
        padding: 20px;
        border: 1px solid #888;
        width: 55%;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    .rules {
        margin-bottom: 20px;
    }
    .rules p {
        margin-bottom: 10px;
    }


    .errorlist {
        color: red;
    }


    .form-group {
        margin-bottom: 20px;
    }
    .form-group label {
        display: block;
        font-weight: bold;
    }
</style>
{% endblock %}

user/templates/user/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h2>Password Change Successful</h2>
    <p>Your password has been successfully changed.</p>
</div>
{% endblock %}

user/templates/user/pin_code_modal.html
<!-- The PIN Confirmation -->
<div class="modal" id="pinCodeModal" tabindex="-1" role="dialog" aria-labelledby="pinCodeModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border border-5 border-success">
            <div class="modal-header">
                <h5 class="modal-title" id="pinCodeModalLabel">Upload Attachment</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" data-bs-target="#pinCodeModal" onclick="closePinCodeModal()" aria-label="Close"></button>
            </div>
            <form>
                {% csrf_token %}
                <div class="modal-body" style="padding-bottom: 20px;">
                    <div class="row">
                        <div class="row" id="pinCodeModalBody">
                            <div class="d-none" id="modalCaller"></div>
                            <div class="form-group pin-container">
                                <div class="text-center text-primary fs-5"> Enter 4 digits PIN and continue </div>
                                <input type="password" onkeypress="return restrictToInteger(event, 'pinError')"
                                       title="Please enter a valid integer (0-9)"
                                       class="form-control form-control-lg text-center fs-4"
                                       style="letter-spacing: 2em;"
                                       placeholder="____"
                                       id="id_pin_code" name="pin_code" maxlength="4" required>
                                <i id="pin-modal" class="pin-toggle pin-toggle-modal bi bi-eye-fill" onclick="togglePasswordVisibility('id_pin_code', 'pin-modal')"></i>
                                <div id="pinError" class="invalid-feedback my-2 text-danger">Please enter a valid integer (0-9).</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" data-bs-target="#pinCodeModal" onclick="closePinCodeModal()"><i class="bi bi-x mx-2"></i>Cancel</button>
                    <button type="button" class="btn btn-success" id="confirmPinCode" disabled><i class="bi bi-check-circle mx-2"></i>Continue</button>

                </div>

            </form>
        </div>
    </div>
</div>

user/templates/user/profile_edit.html
{% extends 'base.html' %}

{% block contentIcon %}
    bi-person-badge
{% endblock %}

{% block contentTitle %}
    Update Profile
{% endblock %}

{% block content %}
<div class="container" style="max-width: 1200px;">  <!-- Increased max-width of the container -->
    <div class="d-flex justify-content-center">
        <div class="card-deck" style="width: 100%; max-width: 1000px;">  <!-- Set a max-width for the card deck -->
            <div class="card" style="width: 100%; margin: 15px; padding: 20px;">  <!-- Increased margin and added padding for height -->
                <div class="card-body">
                    <h4 style="text-align: center; margin: 15; font-size: 24px;"><strong>Edit Profile</strong></h4>
                    <form method="post" enctype="multipart/form-data" style="width: 100%;">  <!-- Set width to 100% -->

                        {% csrf_token %}
                        <div class="form-group" style="display: flex; align-items: center;">
                            <label for="id_bio" style="margin-right: 10px; font-size: 16px;">Bio:</label>
                            {{ profile_form.bio }}
                        </div>

                        <div class="form-group">

                                {% if profile_form.instance.profile_picture %}
                                    <div class="form-group" style="display: flex; align-items: center; margin-right: 0px;">
                                        <span style="margin-right: 5px;">
                                          <a href="{{ profile_form.instance.profile_picture.url }}" target="_blank" style="margin-right: 10px;">
                                                {{ profile_form.instance.profile_picture }}
                                          </a>
                                        </span>
                                        <button type="submit" name="remove_picture" class="btn btn-danger btn-sm" style="margin-left: 0px;">Remove</button>
                                    </div>
                                {% else %}
                                    <strong>Change: </strong> {{ profile_form.profile_picture }}
                                {% endif %}

                            {% if profile_form.instance.profile_picture %}
                                <div class="form-group" style="display: flex; align-items: center; margin-top: 20px;">
                                    <strong style="margin-right: 10px;">Change:</strong>  <!-- Adjusted margin for spacing -->
                                    <input type="file" name="profile_picture" id="id_profile_picture" style="margin-right: 5px; width: auto; flex-grow: 1;">  <!-- Set width to auto and flex-grow for flexibility -->
                                </div>
                            {% endif %}
                        </div>

                        <div style="display: flex; justify-content: center; margin-top: 15px;">
                            <button type="submit" name="update_profile" class="btn btn-primary">Update Profile</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card" style="width: 100%; margin: 15px; padding: 20px;">
                <div class="card-body">
                    <h4 style="text-align: center; margin: 15; font-size: 24px;"><strong>Change Password</strong></h4>
                    <form id="password-change-form" method="post" style="width: 100%;">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="password" name="old_password" class="form-control" id="id_old_password" placeholder="Old Password" required>
                            {% if password_form.old_password.errors %}
                                <div class="text-danger">
                                    {% for error in password_form.old_password.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input type="password" name="new_password1" class="form-control" id="id_new_password1" placeholder="New Password" required>
                            {% if password_form.new_password1.errors %}
                                <div class="text-danger">
                                    {% for error in password_form.new_password1.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input type="password" name="new_password2" class="form-control" id="id_new_password2" placeholder="Confirm New Password" required>
                            {% if password_form.new_password2.errors %}
                                <div class="text-danger">
                                    {% for error in password_form.new_password2.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div style="display: flex; justify-content: center; margin-top: 15px;">
                            <button type="submit" name="change_password" class="btn btn-primary">Change Password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}