dms/urls.py
from django.urls import path, include
from . import views
from .views import send_memo_to_dms

urlpatterns = [
    path('', views.index, name='index'),
    path('document/create/', views.document_create, name='document_create'),
    path('document/<int:pk>/details/', views.document_details, name='document_details'),
    path('document/<int:pk>/update/', views.document_update, name='document_update'),
    path('document/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('search/', views.search_results, name='search'),
    path('dms/document/<int:document_id>/share/', views.share_document, name='share_document'),
    path('send_memo/<int:memo_id>/', send_memo_to_dms, name='send_memo_to_dms'),
    path('list_in_dms/', views.list_in_dms, name='list_in_dms'),
    path('count_memos_sent_to_dms/', views.count_memos_sent_to_dms, name='count_memos_sent_to_dms'),
]

memotracker/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [

    # All memo list
    path('', views.list_all_memo, name='list_all_memo'),
    # Draft memo list
    path('draft_memo_list/', views.draft_memo_list, name='draft_memo_list'),
    # Approved memo list
    path('approved_memo_list/', views.approved_memo_list, name='approved_memo_list'),
    # Sent memo list
    path('sent_memo_list/', views.sent_memo_list, name='sent_memo_list'),
    # Incoming memo list
    path('incoming_memo_list/', views.incoming_memo_list, name='incoming_memo_list'),
    # outgoing memo list
    path('closed_memo_list/', views.closed_memo_list, name='closed_memo_list'),
    # Outgoing memo list
    path('outgoing_memo_list/', views.outgoing_memo_list, name='outgoing_memo_list'),
    # external memo list
    path('external_memo_list/', views.external_memo_list, name='external_memo_list'),
    # Personal memo list
    path('personal_memo_list/', views.personal_memo_list, name='personal_memo_list'),
    # memo details
    path('memo/<int:pk>', views.memo_detail, name='memo_detail'),
    path('memo/<int:pk>/<str:list_name>', views.memo_detail, name='memo_detail'),
    path('memohistory/', views.memohistory, name='memohistory'),
    path('memotracker/<int:memo_id>/', views.memohistory_detail, name='memohistory_detail'),
    # path('history/', views.memohistory, name='memohistory'),
    # path('memotracker/<int:memo_id>/', views.memohistory_detail, name='memohistory_detail'),
    path('create_memo/', views.create_memo, name='create_memo'),
    path('external_memo/', views.external_memo, name='external_memo'),
    path('delete_memo/', views.delete_memo, name='delete_memo'),
    path('edit_memo/<int:memo_id>', views.edit_memo, name='edit_memo'),

    path('memo_route/', views.memo_route, name='memo_route'),
    path('memo_route/<int:memo_id>/', views.memo_route, name='memo_route'),
    path('memo_route2/<int:memo_id>/', views.memo_route2, name='memo_route2'),
    path('memo_route_to_all/', views.memo_route_to_all, name='memo_route_to_all'),
    path('memo_route_to_all/<int:memo_id>/', views.memo_route_to_all, name='memo_route_to_all'),
    path('approval_route/', views.approval_route, name='approval_route'),
    path('approval_route/<int:memo_id>/', views.approval_route, name='approval_route'),
    path('access-denied/', views.access_denied, name='access_denied'),
    path('approve_memo/', views.approve_memo, name='approve_memo'),
    path('memo_attachment_add/<int:memo_id>', views.memo_attachment_add, name='memo_attachment_add'),
    path('memo_attachments_list/<int:pk>/', views.memo_attachments_list, name='memo_attachments_list'),
    path('memo_attachment_delete/', views.memo_attachment_delete, name='memo_attachment_delete'),
    path('memo_attachment_update/<int:memo_id>/<int:attachment_id>/update/', views.memo_attachment_update, name='memo_attachment_update'),
    path('memo_approval_history/<int:memo_id>', views.memo_approval_history, name='memo_approval_history'),
    path('memo_route_history/<int:memo_id>/<str:list_name>', views.memo_route_history, name='memo_route_history'),
    path('external_memo/', views.external_memo, name='external_memo'),
    path('edit_memo_route/<int:pk>/', views.edit_memo_route, name='edit_memo_route'),
    path('delete_memo_route/<str:list_name>', views.delete_memo_route, name='delete_memo_route'),
    path('reverse_memo_route/<str:list_name>', views.reverse_memo_route, name='reverse_memo_route'),
    path('edit_approval_route/<int:pk>/', views.edit_approval_route, name='edit_approval_route'),
    path('delete_memo_approval/', views.delete_memo_approval, name='delete_memo_approval'),
    path('update_attached_memos/', views.update_attached_memos, name='update_attached_memos'),
    path('count_unread_memos/', views.count_unread_memos, name='count_unread_memos'),
    path('count_unread_memos/<str:listName>', views.count_unread_memos, name='count_unread_memos'),
    path('report/<int:memo_id>/<str:format>/', views.generate_report, name='generate_report'),
    # path('download/report/<int:memo_id>/', views.download_report, name='download_report'),
    path('api/memo/<int:pk>/', views.memo_detail_api, name='memo_detail_api'),
    path('show_notifications/', views.show_notifications, name='show_notifications'),

    ]

projectx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user import views

from django.views.generic import TemplateView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter

app_name = 'organogram'

router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('dms/', include('dms.urls'), name='dms'),
    path('organogram/', include('organogram.urls'), name='org'),
    path('memotracker/', include('memotracker.urls'), name='memotracker'),
    path('user/', include('user.urls'), name='user'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('notification/', include('notification.urls'), name='notify'),
    path("firebase-messaging-sw.js", TemplateView.as_view(
        template_name="firebase-messaging-sw.js",
        content_type="application/javascript"
    ), name="firebase-messaging-sw.js"),
    path('api/', include(router.urls)),
    #################################### Memo to DMS
    path('memo/', include(('memotracker.urls', 'memotracker'), namespace='memotracker')),
    path('dms/', include(('dms.urls', 'dms'), namespace='dms')),
    ####################################
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memotracker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from organogram.models import ContentTypeModelField, ExternalCustomer, UserRole, BusinessUnit, Profile
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models import Q
from dms.models import Document
class Memo(models.Model):
    reference_number = models.CharField(max_length=50, unique=True)
    subject = models.CharField(max_length=300)
    content = RichTextUploadingField(blank=True, null=True) 
    memo_date = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='created_by')
    content_type = ContentTypeModelField(ContentType, verbose_name='Owner Type', null=True, on_delete=models.SET_NULL)
    object_id = models.PositiveIntegerField()
    owner = GenericForeignKey('content_type', 'object_id')
    urgent = models.BooleanField(default=False)
    public = models.BooleanField(default=False)
    keywords = models.CharField(max_length=100, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    assigned_to = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='assigned_to')
    status = models.CharField(choices=[
        ('draft', 'Draft'),
        ('approved', 'Approved'),
        ('sent', 'Sent'),
        ('closed', 'Closed')
    ], default='draft')
    due_date = models.DateTimeField(null=True, blank=True)
    attached_memos = models.ManyToManyField('self', blank=True)
    to_external = models.BooleanField(default=False)
    in_english = models.BooleanField(default=False)

    def __str__(self):
        return self.reference_number + ' - ' + self.subject

    def memo_status(self):

        pass

    def get_attached_memo_memos(self):

        if not self.attached_memos.exists():
            return ""

        titles_and_refs = []
        for memo in self.attached_memo.all():
            title_and_ref = f"{memo.title} ({memo.reference_number})"  # Customize format as needed
            titles_and_refs.append(title_and_ref)
        
        return titles_and_refs

    def has_attachments(self):
        return self.attached_memos.count() > 0

    def get_route_status(self, request):
        user_role = UserRole.objects.get(user=request.user, active=True)
        bunit = user_role.business_unit
        manager = user_role.role.is_manager
        delegate = user_role.deligated
        user_type = ContentType.objects.get(model="user", app_label="auth")
        bu_type = ContentType.objects.get(model="businessunit", app_label="organogram")
        if manager or delegate:
            route = self.memoroute_set.filter(Q(destination_id=bunit.id, destination_type=bu_type) |
                                              Q(destination_id=request.user.id, destination_type=user_type)).order_by('-level').first()
        else:
            route = self.memoroute_set.filter(destination_id=request.user.id, destination_type=user_type).order_by('-level').first()
        if route:
            status = route.get_status_display()
        else:
            status = self.get_status_display()
        return status

    def get_memo_owner(self):
        owner = ""
        if self.content_type == ContentType.objects.get(model="user", app_label="auth"):
            profile = Profile.objects.get(user_id=self.object_id)
            if self.in_english:
                owner = profile.user.first_name + " " + profile.user.last_name
            else:
                # owner = profile.full_name_am
                owner = profile.full_name_am if profile.full_name_am else profile.full_name
        elif self.content_type == ContentType.objects.get(model="businessunit", app_label="organogram"):
            bu = BusinessUnit.objects.get(pk=self.object_id)
            if self.in_english:
                owner = bu.name_en
            else:
                owner = bu.name_am
        elif self.content_type == ContentType.objects.get(model="externalcustomer", app_label="organogram"):
            ec = ExternalCustomer.objects.get(pk=self.object_id)
            if self.in_english:
                owner = ec.name_en
            else:
                owner = ec.name_am
        return owner

    def get_memo_destination(self):
        destination = []
        if self.status == "sent":
            routes = self.memoroute_set.filter(level=1, carbon_copy=False)
            if routes:
                destination = self.get_memo_routes(routes)
            else:
                destination.append(self.get_memo_owner())
        else:
            destination.append(self.get_memo_owner())
        return destination

    def get_memo_routes(self, routes):
        destination = []
        dest_length = 0
        for route in routes:
            if route.destination_type.model == 'externalcustomer':
                external = ExternalCustomer.objects.get(pk=route.destination_id)
                if route.memo.in_english:
                    dest = external.name_en
                else:
                    dest = external.name_am
            elif route.destination_type.model == 'user':
                user = User.objects.get(pk=route.destination_id)
                profile = Profile.objects.get(user_id=route.destination_id)
                if route.memo.in_english:
                    dest = profile.user.first_name + " " + profile.user.last_name
                else:
                    dest = profile.full_name
            else:
                business_unit = BusinessUnit.objects.get(pk=route.destination_id)
                if route.memo.in_english:
                    dest = business_unit.name_en
                else:
                    dest = business_unit.name_am

            dest_length += len(dest)

            if dest_length < 50:
                destination.append(dest)
            else:
                destination.append('...')
                break

        return destination

    def get_memo_cc_destination(self):
        destination = []
        if self.status == "sent":
            routes = self.memoroute_set.filter(level=1, carbon_copy=True)
            if routes:
                destination = self.get_memo_routes(routes)
        return destination

    def get_memo_assigned_to(self):
        assigned_to = ""
        if self.assigned_to:
            if self.in_english:
                assigned_to = self.assigned_to.first_name + ' ' + self.assigned_to.last_name
            else:
                profile = Profile.objects.get(user=self.assigned_to)
                if profile and profile.full_name != "":
                    assigned_to = profile.full_name
                else:
                    assigned_to = self.assigned_to.first_name + ' ' + self.assigned_to.last_name
        return assigned_to

class ApprovalRoute(models.Model):
    memo = models.ForeignKey(Memo, on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='approval_source')
    to_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='approval_destination')
    comment = models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.memo.reference_number + ' : ' + self.from_user.first_name + ' -> ' + self.to_user.first_name

    def get_destination(self):
        return self.to_user.first_name + ' ' + self.to_user.last_name

class MemoAction(models.Model):
    description = models.CharField(blank=False, null=False)
    description_am = models.CharField(blank=False, null=False)

    def __str__(self):
        return f'{self.description}' + ' - ' + f'{self.description_am}'
class MemoRoute(models.Model):
    memo = models.ForeignKey(Memo, on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='route_source')
    to_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='route_destination')
    destination_type = ContentTypeModelField(ContentType, verbose_name='Destination Type', null=True, on_delete=models.SET_NULL)
    destination_id = models.PositiveIntegerField(default=0)
    destination = GenericForeignKey('destination_type', 'destination_id')
    level = models.IntegerField(default=1)
    carbon_copy = models.BooleanField(default=False)
    # is_read = models.BooleanField(default=False)
    memo_action = models.ForeignKey(MemoAction, null=True, on_delete=models.SET_NULL)
    remark = models.TextField()
    date_sent = models.DateTimeField(auto_now_add=True)
    date_viewed = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=[
        ('notseen', 'Not Seen'),
        ('seen', 'Seen'),
        ('reversed', 'Reversed'),
        ('forwarded', 'Forwarded'),
        ('closed', 'Closed')
    ], default='notseen')

    def __str__(self):
        app_label = 'auth'
        model_name = 'user'
        destination_type = ContentType.objects.get(app_label=app_label, model=model_name)

        try:
            if self.destination_type == ContentType.objects.get(model='externalcustomer'):
                external = ExternalCustomer.objects.get(pk=self.destination_id)
                return f"{self.memo.reference_number} : {self.from_user.first_name} -> {external.name_en}"
            elif self.destination_type == destination_type:
                user = User.objects.get(pk=self.destination_id)
                return f"{self.memo.reference_number} : {self.from_user.first_name} -> {user.first_name}"
            else:
                bu = BusinessUnit.objects.get(pk=self.destination_id)
                return f"{self.memo.reference_number} : {self.from_user.first_name} -> {bu.name_en}"
        except ExternalCustomer.DoesNotExist:

memotracker/templates/memotracker/access_denied.html
<!-- access_denied.html -->
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>Access Denied</h1>
    <p>Sorry, you do not have the necessary permissions to access this page.</p>
    <!-- You can customize the message or styling as per your design -->
</div>
{% endblock %}

memotracker/templates/memotracker/memo_attachment_add.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block content %}
<div class="container">
    <h2> Add Memo Attachment </h2>
    <p> <strong> Memo: </strong> <a href="{% url 'memo_detail' memo_id %}">({{memo.reference_number}}) - {{ memo.subject}} </a> </p>
    <p class="mt-5"> <strong> Attachment: </strong> </p>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
            <label for="id_document" class="col-sm-2 col-form-label">Document</label>
            <div class="row mb-3">
                <div class="col-9">
                    {{form.document}}

                </div>
                <div class="col-3 d-flex align-items-center mb-0">
                    <button type="button" onclick="uploadDocument('{% url 'document_create' %}', 'add_document', 'New document');" class="btn btn-success" data-toggle="modal" data-target="#attachmentModal">
                        <i class="bi bi-file-earmark-plus"></i> Add
                    </button>
                </div>
                {% if form.document.errors %}
                        <div class="text-danger small mt-1">
                            {{ form.document.errors.0 }}
                        </div>
                    {% endif %}
            </div>

            <label for="id_permission" class="col-sm-2 col-form-label">Permission</label>
            <div class="row mb-3">
                <div class="col-sm-9">
                    {{form.permission}}
                </div>
            </div>
            <label for="id_remark" class="col-sm-2 col-form-label">Remark</label>
            <div class="row mb-3">
                <div class="col-sm-9">
                    {{form.remark}}
                </div>
            </div>

            <div class="d-flex gap-3 justify-content-center">
                <a href="{% url 'memo_attachments_list' memo_id %}" class="btn btn-secondary"><i class="bi bi-x"></i>Cancel</a>
                <button type="submit" class="btn btn-primary"> <i class="bi bi-paperclip"></i> Attach </button>
            </div>
    </form>

   {% include 'modal.html' %}

   <script>
        window.addEventListener('load', function() {
        const savedDocument = localStorage.getItem('savedDocument');

        if (savedDocument) {
            const cur_doc = document.getElementById('id_document');

            /* adds the last entry in the select options as the
                selected option since it is the most recent
            */
            cur_doc.options[cur_doc.options.length-1].selected = true;
            // Remove savedDocument from localStorage
            localStorage.removeItem('savedDocument');
        }
    });
   </script>

{% endblock %}
</div>

memotracker/templates/memotracker/memo_attachment_update.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}

<!-- Update Memo Attachment -->
<div class="container">
    <h2> Update Memo Attachment </h2>
    <p> <strong> Attachment: </strong> </p>
   
    <form method="post" action="{% url 'memo_attachment_update' memo_id=attachment.memo.id attachment_id=attachment.id %}">
        {% csrf_token %}
        {{ form.media }}
            <div class="row mb-3">
                
                <div class="col-10">
                    {{form.attached_by}}
                </div>
            </div>
            <div class="row mb-3">
                <label for="id_document" class="col-sm-2 col-form-label">Document</label>
                <div class="col-sm-10">
                    {{form.document}}
                </div>
            </div>

            <div class="row mb-3">
                <label for="id_permission" class="col-sm-2 col-form-label">Permission</label>
                <div class="col-sm-10">
                {{form.permission}}
                </div>
            </div>
            <div class="row mb-3">
                <label for="id_permission" class="col-sm-2 col-form-label">Remark</label>
                <div class="col-sm-10">
                {{form.remark}}
                </div>
            </div>

            <div class="d-flex gap-3 justify-content-center">
                <a href="{% url 'memo_attachments_list' memo_id %}" class="btn btn-secondary"><i class="bi bi-x"></i>Cancel</a>
                <button type="submit" class="btn btn-primary"> <i class="bi bi-paperclip"></i> Update </button>
            </div>
         
    </form>
{% endblock %}

memotracker/templates/memotracker/memo_attachments_list.html
{% extends 'base.html' %}
{% block title %}Memo Attachments {% endblock %}
{% block contentTitle %} Memo Attachments {% endblock %}
{% block backBtn %}
    <a href="#" id="backFromAttachment" class="icon-link icon-link-hover">
        <i class="bi bi-arrow-left mx-1"></i>
    </a>
{% endblock %}

{% load static %}

{% block content %}
<script>
    let backBtnUrl = localStorage.getItem('backBtnUrl');
</script>

<p> <strong> Memo: </strong> <a href="{% url 'memo_detail' memo.id %}">({{memo.reference_number}}) {{ memo.subject}} </a> </p>
<p class="text-end mb-3">
    <a href="{% url 'memo_attachment_add' memo.id %}" class="btn btn-primary"><i class="bi bi-paperclip"></i> Add</a>
</p>


{% if attachments %}
<div class="row table-responsive">
    <table class="table table-striped table-hover">
        <thead class="table-success">
            <tr>
                <th> S.No </th>
                <th> Attachment </th>
                <th> Attached By </th>
                <th> Permission </th>
                <th> Remark </th>
                <th> Actions </th>
            </tr>
        </thead>
    <tbody>
        {% for attachment in attachments %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
                <a href = " {{ attachment.document.file.url }} " target="_blank"> <i class="bi bi-eye me-2"></i>{{ attachment.document.title }}</a>
            </td>
            <td>
                {% for attachment in memo.attachments.all %}
                    {{ attachment.get_attached_by_display }}
                {% endfor %}
            </td>
            <td> {{ attachment.permission}}</td>
            <td> {% if attachment.remark %}
                {{ attachment.remark }}
                {% else %}
                <span class="text-muted"> No remark </span>
                {% endif %}
            </td>
            <td>
               <a href="{% url 'memo_attachment_update' memo_id=attachment.memo.id attachment_id=attachment.id %}" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                    <a class="btn btn-hover btn-danger" href="#"
                        data-bs-toggle="modal" data-bs-target="#confirmationModal"
                        data-bs-action="attachment_delete" data-record-id="{{  attachment.id }}"
                        data-modal-body-class="text-danger"
                        data-bs-title="Delete Attachment" data-bs-body="Are you sure to delete attachment '{{ attachment.document.title }}'?">
                        <i class="bi bi-trash3-fill"></i>
                    </a>

            </td>

        </tr>
        {% endfor %}
    </tbody>
    
{% else %}
    <h5> No attachments for this memo </h5>
{% endif %}
</table>
</div>

    <script>
        let baseUrl = window.location.protocol + '//' + window.location.host + '/memotracker/';
        let backFromAttachment = document.getElementById('backFromAttachment');
        backFromAttachment.setAttribute('href', baseUrl + backBtnUrl);
        let span = document.createElement('span');
        let backBtnLabel = "";
        switch(backBtnUrl) {
            case 'draft_memo_list':
                backBtnLabel = "Draft Memos";
                break;
            case 'outgoing_memo_list':
                backBtnLabel = "Outgoing Memos";
                break;
            case 'personal_memo_list':
                backBtnLabel = "Personal Memos";
                break;
            case 'incoming_memo_list':
                backBtnLabel = "Incoming Memos";
                break;
            case 'external_memo_list':
                backBtnLabel = "External Memos";
                break;
        }
        span.innerHTML = backBtnLabel;
        span.style.fontWeight = "bold";
        backFromAttachment.appendChild(span);
    </script>

{% endblock %}

memotracker/templates/memotracker/memohistory.html
{% extends 'base.html' %}
{% block title %} Update Document {% endblock %}
{% block contentIcon %}
    bi-clock-history
{% endblock %}
{% block contentTitle %}
    Memo History
{% endblock %}

{% block content %}
    <style>


        .content {
            margin-left: 30px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin-left: 15px;
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">S.No</th>
                <th>Reference Number</th>
                <th>Subject</th>
                <th>Created By</th>
                <th>Routing Info</th>
            </tr>
        </thead>
        <tbody>
            {% for memo in memos_with_routes %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ memo.reference_number }}</td>
                    <td>{{ memo.subject }}</td>
                    <td>{{ memo.created_by.first_name }} {{ memo.created_by.last_name }}</td>
                    <td><a href="{% url 'memohistory_detail' memo.id %}">Tracking History</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

memotracker/templates/memotracker/route_modal.html
<!-- The Routing Modal -->
<div class="modal" id="routeModal" tabindex="-1" role="dialog" aria-labelledby="routeModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="routeModalLabel">Upload Attachment</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" data-bs-target="#routeModal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-1">&nbsp;</div>
                    <div class="col-lg-10" id="routeModalBody"></div>
                    <div class="col-lg-1">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</div>

memotracker/templates/memotracker/toast.html
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <img src="..." class="rounded me-2" alt="...">
        <strong class="me-auto">Bootstrap</strong>
        <small>11 mins ago</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        Hello, world! This is a toast message.
      </div>
    </div>
  </div>

  <button type="button" class="btn btn-primary" id="liveToastBtn">Show live toast</button>