dms/urls.py
from django.urls import path, include
from . import views
from .views import send_memo_to_dms

urlpatterns = [
    path('', views.index, name='index'),
    path('document/create/', views.document_create, name='document_create'),
    path('document/<int:pk>/details/', views.document_details, name='document_details'),
    path('document/<int:pk>/update/', views.document_update, name='document_update'),
    path('document/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('search/', views.search_results, name='search'),
    path('dms/document/<int:document_id>/share/', views.share_document, name='share_document'),
    path('send_memo/<int:memo_id>/', send_memo_to_dms, name='send_memo_to_dms'),
    path('list_in_dms/', views.list_in_dms, name='list_in_dms'),
    path('count_memos_sent_to_dms/', views.count_memos_sent_to_dms, name='count_memos_sent_to_dms'),
]

projectx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user import views

from django.views.generic import TemplateView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter

app_name = 'organogram'

router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('dms/', include('dms.urls'), name='dms'),
    path('organogram/', include('organogram.urls'), name='org'),
    path('memotracker/', include('memotracker.urls'), name='memotracker'),
    path('user/', include('user.urls'), name='user'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('notification/', include('notification.urls'), name='notify'),
    path("firebase-messaging-sw.js", TemplateView.as_view(
        template_name="firebase-messaging-sw.js",
        content_type="application/javascript"
    ), name="firebase-messaging-sw.js"),
    path('api/', include(router.urls)),
    #################################### Memo to DMS
    path('memo/', include(('memotracker.urls', 'memotracker'), namespace='memotracker')),
    path('dms/', include(('dms.urls', 'dms'), namespace='dms')),
    ####################################
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organogram/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django import forms
from projectx import settings


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class BusinessUnit(models.Model):
    code = models.CharField(max_length=10)
    name_am = models.CharField(verbose_name='Name(am)', max_length=200)
    name_en = models.CharField(verbose_name='Name(en)', max_length=200)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='children')
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    bu_signature = models.ImageField(upload_to='digital_signature/', blank=True, null=True)
    location = models.CharField(max_length=150)
    contact = models.CharField(max_length=100)
    last_memo_ref_number = models.IntegerField(default=0)
    # New fields for headers and footers
    internal_header_image = models.ImageField(upload_to='headers/internal/', blank=True, null=True)
    external_header_image = models.ImageField(upload_to='headers/external/', blank=True, null=True)
    internal_footer_image = models.ImageField(upload_to='footers/internal/', blank=True, null=True)
    external_footer_image = models.ImageField(upload_to='footers/external/', blank=True, null=True)
    class Meta:
        ordering = ['name_en']

    def __str__(self):
        return f"{self.code} - {self.name_en}"

class Role(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    is_manager = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
class UserRole(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    business_unit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField()
    deligated = models.BooleanField()

    def __str__(self):
        return self.user.username + ' - ' + self.role.name + ' - ' + self.business_unit.code

class ExternalCustomer(models.Model):
    name_am = models.CharField(verbose_name='Name(am)', max_length=200)
    name_en = models.CharField(verbose_name='Name(en)', max_length=200)
    description = models.CharField(max_length=300, blank=True, null=True)
    contact = models.CharField(max_length=100, blank=True, null=True)
    customer_type = models.CharField(choices = [
        ('Org', 'Organization'),
        ('Ind', 'Individual'),
    ])

    class Meta:
        ordering = ['name_en']

    def __str__(self):
        return self.name_en + ' - ' + self.name_am

CUSTOM_DISPLAY_NAMES = {
    'user': 'Personal',
    'businessunit': 'Business Unit',
    'externalcustomer': 'External',
}

class CustomModelNameChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        model_name = obj.model.lower()
        return CUSTOM_DISPLAY_NAMES.get(model_name, obj.model)

class ContentTypeModelField(models.ForeignKey):
    def formfield(self, **kwargs):
        defaults = {
            'form_class': CustomModelNameChoiceField,
            'queryset': ContentType.objects.filter(
                models.Q(app_label='auth', model='user') |
                models.Q(app_label='organogram', model='businessunit') |
                models.Q(app_label='organogram', model='externalcustomer')
            )
        }
        defaults.update(kwargs)
        return super().formfield(**defaults)

class PermissionParent(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
class Permission(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=100, blank=True)
    display_name = models.CharField(max_length=50)
    icon = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    parent = models.ForeignKey(PermissionParent,blank=True, null=True, on_delete=models.SET_NULL)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.display_name


class RolePermission(models.Model):
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    permission = models.ForeignKey(Permission, on_delete=models.CASCADE)

    class Meta:
        ordering = ['permission__order']
    def __str__(self):
        return self.role.name + ' - ' + self.permission.name
class Profile(models.Model):
    SECURITY_QUESTIONS = [
        ("Your birth year", "Your birth year"),
        ("Your grandmother's name", "Your grandmother's name"),
        ("Name of your elementary school", "Name of your elementary school"),
        ("Your favorite color", "Your favorite color"),
        ("Your first pet's name", "Your first pet's name"),
        ("City where you were born", "City where you were born"),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=150, blank=True)
    full_name_am = models.CharField(max_length=150, blank=True) ########
    pin_code = models.CharField(max_length=128, null=True)
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to=settings.DOCUMENT_PATH)
    password_set = models.BooleanField(default=False)
    preference = models.JSONField(default=dict)
    security_question_1 = models.CharField(max_length=100, choices=SECURITY_QUESTIONS, default="Your birth year")
    security_answer_1 = models.CharField(max_length=100, null=True, blank=True)
    security_question_2 = models.CharField(max_length=100, choices=SECURITY_QUESTIONS, null=True, blank=True,
                                               default="Your grandmother's name")
    security_answer_2 = models.CharField(max_length=100, null=True, blank=True)
    security_question_3 = models.CharField(max_length=100, choices=SECURITY_QUESTIONS, null=True, blank=True,
                                               default="Name of your elementary school")
    security_answer_3 = models.CharField(max_length=100, null=True, blank=True)
    last_personal_memo_ref_number = models.IntegerField(default=0)

    # Add more fields as per your requirements

    def __str__(self):
        return self.user.username

templates/confirmation-dialog.html
<div class="modal fade" data-action="" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="confirmationModalLabel">
            Modal Title
        </h1>
      </div>
      <div class="modal-body" id="confirmationModalBody" data-bs-class="modal-body">
          <p>Modal Body</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <button type="button" class="btn btn-primary" id="confirmationYesButton">Yes</button>
      </div>
    </div>
  </div>
</div>

templates/footer.html
<div class="copyright-text text-center">
    <p style="font-size: 10px;">Copyright © {% now "Y" %}
        <a style="font-size: 10px;" href="https://ipdc.gov.et" target="_blank">IPDC</a>.
         All Right Reserved.
    </p>
</div>

templates/modal.html
<!-- The Attachment Modal -->
<div class="modal" id="modalContainer" tabindex="-1" role="dialog" aria-labelledby="attachmentModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Upload Attachment</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal_body">
                <!-- Add a form for attachment upload here -->
                
            </div>
        </div>
    </div>
</div>

templates/search_results.html
{% block content %}
<h1>Please, check search is working...</h1>
{% endblock %}

templates/sidebar.html
{% if user.is_authenticated %}
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

        <li class="nav-item has-treeview {% if request.path|slice:'1:12' == 'memotracker' or request.path|slice:'1:12' == '' or request.path|slice:'1:5' == 'user' %}
                {% if 'approved_memo_list' in request.path or 'memohistory' in request.path or 'personal_memo_list' in request.path or 'customer' in request.path %}
                {% else %}
                    menu-open
                {% endif %}
            {% endif %}"
        >
            <a href="#" class="nav-link">
                <i class="bi bi-envelope-paper-fill menu-icon"></i>
                <p>
                    Memo Tracker System
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                {% for user_role in user.userrole_set.all %}
                    {% for role_perm in user_role.role.rolepermission_set.all %}
                        {% if role_perm.permission.parent.code == "MTS" %}
                             <li class="nav-item">
                                <a href="/{{ role_perm.permission.url }}/" class="nav-link">
                                    &nbsp;&nbsp;&nbsp;<i class="bi {{ role_perm.permission.icon }}"></i>&nbsp;
                                    <p>{{ role_perm.permission.display_name }}</p>
                                    {% if role_perm.permission.display_name == 'Incoming Memo' %}
                                        <script>
                                            loadIncomingUnreadCount();
                                            function loadIncomingUnreadCount() {
                                                let url = "/memotracker/count_unread_memos/Incoming Memo";
                                                fetch(url, {
                                                    method: 'GET'
                                                })
                                                .then(response => response.json())
                                                .then(data => {
                                                    let count = JSON.parse(data.count);
                                                    let incomingUnread = document.getElementById('incomingUnread');
                                                    if (incomingUnread && count !== 0) {
                                                        incomingUnread.innerHTML = count;
                                                        incomingUnread.style.display = 'inline-block';
                                                    }
                                                });
                                            }
                                        </script>
                                        <span id="incomingUnread" class="badge text-bg-primary rounded-pill" style="font-size: 15px; display: none;">
                                        </span>
                                    {% elif role_perm.permission.display_name == 'External Letter' %}
                                        <script>
                                            loadExternalUnreadCount();
                                            function loadExternalUnreadCount() {
                                                let url = "/memotracker/count_unread_memos/External Letter";
                                                fetch(url, {
                                                    method: 'GET'
                                                })
                                                .then(response => response.json())
                                                .then(data => {
                                                    let count = JSON.parse(data.count);
                                                    let externalUnread = document.getElementById('externalUnread');
                                                    if (externalUnread && count !== 0) {
                                                        externalUnread.innerHTML = count;
                                                        externalUnread.style.display = 'inline-block';
                                                    }
                                                });
                                            }
                                        </script>
                                        <span id="externalUnread" class="badge text-bg-primary rounded-pill" style="font-size: 15px; display: none;">
                                        </span>
                                    {% elif role_perm.permission.display_name == 'Draft Memo' %}
                                        <script>
                                            loadDraftUnreadCount();
                                            function loadDraftUnreadCount() {
                                                let url = "/memotracker/count_unread_memos/Draft Memo";
                                                fetch(url, {
                                                    method: 'GET'
                                                })
                                                .then(response => response.json())
                                                .then(data => {
                                                    let count = JSON.parse(data.count);
                                                    let draftUnread = document.getElementById('draftUnread');
                                                    if (draftUnread && count !== 0) {
                                                        draftUnread.innerHTML = count;
                                                        draftUnread.style.display = 'inline-block';
                                                    }
                                                });
                                            }
                                        </script>
                                        <span id="draftUnread" class="badge text-bg-primary rounded-pill" style="font-size: 15px; display: none;">
                                        </span>
                                    {% endif %}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </ul>
        </li>


        <li class="nav-item has-treeview {% if request.path|slice:'1:4' == 'dms' %}menu-open{% endif %}">
            <a href="#" class="nav-link">
                <i class="bi bi-file-earmark-pdf-fill menu-icon"></i>
              <p>
                DMS
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
                    {% for user_role in user.userrole_set.all %}
                        {% for role_perm in user_role.role.rolepermission_set.all %}
                            {% if role_perm.permission.parent.code == "DMS" %}
                                <li class="nav-item">
                                    <a href="/{{ role_perm.permission.url }}/" class="nav-link">
                                        &nbsp;&nbsp;&nbsp;<i class="bi {{ role_perm.permission.icon }}"></i>&nbsp;
                                        <p>{{ role_perm.permission.display_name }}</p>
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </ul>
        </li>


        <li class="nav-item has-treeview
            {% if request.path|slice:'1:12' == 'memotracker' %}
                {% if 'personal' in request.path or 'approved' in request.path or 'memohistory' in request.path %}
                    menu-open
                {% endif %}
            {% elif request.path|slice:'1:11' == 'organogram' %}
                {% if 'customer' in request.path %}
                    menu-open
                {% endif %}
            {% endif %}">
            <a href="#" class="nav-link">
                <i class="bi bi-clipboard2-data-fill menu-icon"></i>
                <p>
                    Reports
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                {% for user_role in user.userrole_set.all %}
                    {% for role_perm in user_role.role.rolepermission_set.all %}
                        {% if role_perm.permission.parent.code == "rpt" %}
                            <li class="nav-item">
                                <a href="/{{ role_perm.permission.url }}/" class="nav-link">
                                    &nbsp;&nbsp;&nbsp;<i class="bi {{ role_perm.permission.icon }}"></i>&nbsp;
                                    <p>{{ role_perm.permission.display_name }}</p>
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </ul>
        </li>

    </ul>
{% endif %}

templates/toaster-message.html
<div class="toast-container position-fixed top-0 end-0 p-3">
    <div id="generalToast" class="toast text-white" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <i class="bi"></i>
        <span class="mx-2"></span>
        <strong class="me-auto" id="id_toast_header"></strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body" id="id_toast_body">
      </div>
    </div>
</div>