dms/urls.py
from django.urls import path, include
from . import views
from .views import send_memo_to_dms

urlpatterns = [
    path('', views.index, name='index'),
    path('document/create/', views.document_create, name='document_create'),
    path('document/<int:pk>/details/', views.document_details, name='document_details'),
    path('document/<int:pk>/update/', views.document_update, name='document_update'),
    path('document/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('search/', views.search_results, name='search'),
    path('dms/document/<int:document_id>/share/', views.share_document, name='share_document'),
    path('send_memo/<int:memo_id>/', send_memo_to_dms, name='send_memo_to_dms'),
    path('list_in_dms/', views.list_in_dms, name='list_in_dms'),
    path('count_memos_sent_to_dms/', views.count_memos_sent_to_dms, name='count_memos_sent_to_dms'),
]

projectx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user import views

from django.views.generic import TemplateView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter

app_name = 'organogram'

router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('dms/', include('dms.urls'), name='dms'),
    path('organogram/', include('organogram.urls'), name='org'),
    path('memotracker/', include('memotracker.urls'), name='memotracker'),
    path('user/', include('user.urls'), name='user'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('notification/', include('notification.urls'), name='notify'),
    path("firebase-messaging-sw.js", TemplateView.as_view(
        template_name="firebase-messaging-sw.js",
        content_type="application/javascript"
    ), name="firebase-messaging-sw.js"),
    path('api/', include(router.urls)),
    #################################### Memo to DMS
    path('memo/', include(('memotracker.urls', 'memotracker'), namespace='memotracker')),
    path('dms/', include(('dms.urls', 'dms'), namespace='dms')),
    ####################################
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dms/models.py
import logging
import os

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from pdf2image.exceptions import PDFPageCountError

from organogram.models import ContentTypeModelField, Profile, BusinessUnit, ExternalCustomer
from django.conf import settings
from django.contrib.auth.models import User
from easy_thumbnails.files import get_thumbnailer
from pdf2image import convert_from_path


# Create your models here.
class DocumentCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        verbose_name_plural = "Document Categories"

    def __str__(self):
        return self.name

class Document(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    document_number = models.CharField(max_length=100, unique=True)
    # author = models.CharField(max_length=100, blank=True, null=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, related_name="documents_uploaded")
    privacy = models.CharField(choices=[
        ('public', 'Public'),
        ('private', 'Private')],
        default='private',
        max_length=15)
    description = models.TextField()
    content_type = ContentTypeModelField(ContentType, verbose_name='Owner Type', null=True, on_delete=models.SET_NULL)
    object_id = models.PositiveIntegerField()
    owner = GenericForeignKey('content_type', 'object_id')
    category = models.ForeignKey(DocumentCategory, on_delete=models.SET_NULL, null=True, blank=True, related_name="categories")
    created_date = models.DateField(blank=True, null=True)
    encryption_key = models.CharField(max_length=100, blank=True, null=True)
    file = models.FileField(upload_to=settings.DOCUMENT_PATH)
    # keywords = models.TextField(blank=True, null=True)
    uploaded_date = models.DateTimeField(auto_now_add=True)

    shared_with = models.ManyToManyField(User, through='SharedDocument', related_name='documents_shared_with')

    class Meta:
        permissions = [
            ("can_create_document", "Can create document"),
            ("can_share_document", "Can share document"),
            ("can_update_document", "Can update document"),
            ("can_delete_document", "Can delete document"),
        ]

    def __str__(self):
        return self.title

    def get_owner_name(self, in_english=True):
        owner = ""

        if self.content_type == ContentType.objects.get(model="user", app_label="auth"):
            profile = Profile.objects.get(user_id=self.uploaded_by)
            if in_english:
                owner = f"{profile.user.first_name} {profile.user.last_name}"
            else:
                owner = profile.full_name

        elif self.content_type == ContentType.objects.get(model="businessunit", app_label="organogram"):
            bu = BusinessUnit.objects.get(pk=self.object_id)
            owner = bu.name_en if in_english else bu.name_am

        elif self.content_type == ContentType.objects.get(model="externalcustomer", app_label="organogram"):
            ec = ExternalCustomer.objects.get(pk=self.object_id)
            owner = ec.name_en if in_english else ec.name_am

        return owner


    def get_thumbnail(self):
        file_extension = self.file.name.split('.')[-1]
        if file_extension.lower() == 'pdf':
            pages = convert_from_path(self.file.path)
            if pages:
                page_image = pages[0]
                try:
                    thumbnail_options = {'size': (100, 100)}

                    thumbnail = page_image.copy()
                    thumbnail.thumbnail(thumbnail_options['size'])
                    thumbnail_path = f"{self.file.path}_thumbnail.jpg"
                    thumbnail.save(thumbnail_path)
                    thumbnail_url = f"/media/Documents/{self.file.name.split('/')[-1]}_thumbnail.jpg"

                    return thumbnail_url
                except Exception as e:
                    print(f"Error saving image: {e}")
            return None
        else:
            thumbnailer = get_thumbnailer(self.file)
            thumbnail_options = {'size': (100, 100)}
            thumbnail = thumbnailer.get_thumbnail(thumbnail_options)
            return thumbnail.url
class SharedDocument(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name='shared_documents')
    shared_with = models.ForeignKey(User, on_delete=models.CASCADE, related_name='shared_documents_from')
    shared_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('document', 'shared_with')  # Prevent duplicate shares

    # def __str__(self):
    #     return f"{self.document.title} shared with {self.shared_with.username} on {self.shared_at}"

    def __str__(self):
        shared_with_username = self.shared_with.username if self.shared_with else "Unknown User"
        return f"{self.document.title} shared with {shared_with_username} on {self.shared_at}"

class MemoToDMS(models.Model):
    memo = models.ForeignKey('memotracker.Memo', on_delete=models.CASCADE, related_name="memo_details")
    sent_date = models.DateTimeField(auto_now_add=True)
    sent_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # remarks = models.TextField(blank=True, null=True)

    # def __str__(self):
    #     return f'MemoDetail for {self.memo.reference_number} - Sent by {self.sent_by.username} on {self.sent_date}'

    def __str__(self):
        sent_by_username = self.sent_by.username if self.sent_by else "Unknown Sender"
        return f'MemoDetail for {self.memo.reference_number} - Sent by {sent_by_username} on {self.sent_date}'

dms/forms.py
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
from .models import Document  # Ensure you import your Document model

class DocumentForm(forms.ModelForm):
    shared_with = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple  # Optional: Change to your preferred widget
    )
    # keywords = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), required=False)
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), required=False)
    # Make document_date readonly
    uploaded_date = forms.DateField(initial=timezone.now().date, widget=forms.DateInput(attrs={'type': 'date', 'readonly': 'readonly'}), required=True)

    class Meta:
        model = Document
        exclude = ['object_id', 'uploaded_by']

    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)

        # Add Bootstrap classes to the form fields
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

dms/templates/dms/document_create.html
{% extends 'base.html' %}

{% block title %} Add Document {% endblock %}

{% block content %}
<style>
    textarea.form-control {
    height: auto;
    width: 500px;
}
</style>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <h2 class="text-center"> Upload Document</h2>
    <form method="post" enctype="multipart/form-data" id="add_document">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <label for="id_title" class="form.label"> Title:<span style="color: red;">*</span></label>
                {{form.title}}
            </div>
            <div class="col">
                <label for="id_document_number" class="form.label"> Document Number:<span style="color: red;">*</span></label>
                {{form.document_number}}
            </div>
<!--            <div class="col">-->
<!--                <label for="id_author" class="form.label"> Author:<span style="color: red;">*</span></label>-->
<!--                {{form.author}}-->
<!--            </div>-->
            <div class="col">
                <label for="id_privacy" class="form.label"> Privacy:<span style="color: red;">*</span></label>
                {{form.privacy}}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label for="id_file" class="form.label"> File:<span style="color: red;">*</span></label>
                {{form.file}}
            </div>
            <div class="col">
                <label for="id_content_type" class="form.label"> Owner Type:<span style="color: red;">*</span></label>
                {{form.content_type}}
            </div>
            <div class="col">
                <label for="id_category" class="form.label"> Category:</label>
                {{form.category}}
            </div>
            <div class="col">
                <label for="document_date" class="form.label"> Uploaded Date:<span style="color: red;">*</span></label>
                {{form.uploaded_date}}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label for="description"> Description</label>
                {{form.description}}
            </div>
<!--            <div class="col">-->
<!--                <label for="description"> Keywords</label>-->
<!--                {{form.keywords}}-->
<!--            </div>-->
        </div>
        <div class="d-flex justify-content-end gap-3 my-3">
            <a href="{% url 'index' %}" type="submit" class="btn btn-secondary d-flex-end"> <i class="bi bi-x"></i>Cancel</a>
            <button type="submit" class="btn btn-success d-flex-end"> <i class="bi bi-cloud-upload mx-2"></i>Upload</button>

        </div>
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Set required attributes for mandatory fields
            document.querySelector('#id_title').setAttribute('required', 'required');
            document.querySelector('#id_document_number').setAttribute('required', 'required');
            // document.querySelector('#id_author').setAttribute('required', 'required');
            document.querySelector('#id_privacy').setAttribute('required', 'required');
            document.querySelector('#id_file').setAttribute('required', 'required');
            document.querySelector('#id_document_date').setAttribute('required', 'required');

            // Ensure optional fields are not required
            document.querySelector('#id_category').removeAttribute('required');
            document.querySelector('#id_description').removeAttribute('required');
            // document.querySelector('#id_keywords').removeAttribute('required');

            // Event listener for Send to DMS button
        });
    </script>
{% endblock %}

dms/templates/dms/document_share.html
{% extends 'base.html' %}
{% block title %} Share Document {% endblock %}
{% block contentIcon %}
    bi-share
{% endblock %}
{% block contentTitle %}
    Share Document
{% endblock %}

{% block content %}

    <div class="container" style="margin-left: 20px; margin-top: 20px;"> <!-- Adjust the margin values as needed -->
    <form method="post" id="shareForm">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <p><strong>Title:</strong> {{ document.title }}</p>
                </div>
                <div class="mb-3">
                    <p><strong>Document Number:</strong> {{ document.document_number }}</p>
                </div>
                <div class="mb-3">
                    <p><strong>Uploaded by:</strong> {{ document.uploaded_by.first_name }} {{ document.uploaded_by.last_name }}</p>
                </div>
                <div class="mb-3">
                    <p><strong>Category:</strong> {% if document.category %}{{ document.category.name }}{% else %}None{% endif %}</p>
                </div>
                <div class="mb-3">
                    <p><strong>Privacy:</strong> {{ document.get_privacy_display }}</p>
                </div>
                <div class="mb-3">
                    <p><strong>Doc. Owner: </strong>{% if document.owner %}{{ document.get_owner_name }}{% else %} External {% endif %}</p>
                </div>
                <div class="mb-3">
                    <p><strong>Created Date:</strong> {% if document.created_date %}{{ document.created_date }}{% else %}None{% endif %}</p>
                </div>
                <div class="mb-3">
                    <p><strong>Uploaded Date:</strong> {% if document.uploaded_date %}{{ document.uploaded_date }}{% else %}None{% endif %}</p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="shared_with"><strong>Share with:</strong></label>

                    <select name="shared_with" id="shared_with" multiple class="form-select" style="width: 70%; height: 280px; border: 2px solid black; padding-right: 20px; box-sizing: border-box;">

                        {% for user in users %}
                            <option value="{{ user.id }}">
                                {% if user.first_name or user.last_name %}
                                    {{ user.first_name }} {{ user.last_name }}
                                    {% if user.business_unit_code %}
                                        [{{ user.business_unit_code }}]
                                    {% endif %}
                                {% else %}
                                    {{ user.username }}
                                    {% if user.business_unit_code %}
                                        [{{ user.business_unit_code }}]
                                    {% endif %}
                                {% endif %}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-6 d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary me-2" style="width: 100px;">Share</button>
                    <a href="{% url 'index' %}" class="btn btn-dark download-link" style="width: 100px;">
                        <i class="bi bi-x-circle me-2"></i>Cancel
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Display Django messages as alerts
        if (typeof djangoMessages !== 'undefined') {
            djangoMessages.forEach(function(msg) {
                alert(msg);
            });
        }

        // Document privacy status
        var documentPrivacy = "{{ document_privacy }}";

        // Pre-process already shared user IDs
        var alreadySharedUserIds = [
            {% for shared_user in document.shared_with.all %}
                "{{ shared_user.id }}",
            {% endfor %}
        ];

        document.getElementById('shareForm').onsubmit = function(event) {
            // Check if the document is private
            if (documentPrivacy === 'private') {
                event.preventDefault(); // Prevent form submission
                alert("Private document cannot be shared!"); // Alert message
                window.location.href = "{% url 'index' %}"; // Redirect to index after alert
                return;

            }

            var sharedWith = document.getElementById('shared_with');
            var selectedUsers = Array.from(sharedWith.selectedOptions);

            // Check if users are selected
            if (selectedUsers.length === 0) {
                event.preventDefault(); // Prevent form submission
                alert("Please select at least one user to share the document with!");
                return;
            }

            // Check for already shared users
            var alreadySharedUsers = [];
            var newShareAllowed = true; // Flag to allow sharing

            selectedUsers.forEach(function(option) {
                var userId = option.value;

                if (alreadySharedUserIds.includes(userId)) {
                    alreadySharedUsers.push("The document has already been shared with " + option.text + "!");
                    newShareAllowed = false; // Prevent sharing if any user is already shared
                }
            });

            // Alerts for already shared users
            if (alreadySharedUsers.length > 0) {
                event.preventDefault(); // Prevent form submission
                alreadySharedUsers.forEach(function(msg) {
                    alert(msg);
                });
            }

            // If no already shared users, display success message
            if (newShareAllowed) {
                alert("Document shared successfully!");
            }

            // Prevent form submission if there are no new shares allowed
            if (!newShareAllowed) {
                event.preventDefault(); // Prevent form submission
            }
        };
    });
</script>
{% endblock %}

dms/templates/dms/document_update.html
{% extends 'base.html' %}

{% block title %} Update Document {% endblock %}
{% block contentIcon %}
    bi bi-pencil
{% endblock %}
{% block contentTitle %}
    Update Document
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" id="update-document-form">
        {% csrf_token %}

        <div class="row">
            <div class="col">
                <label for="id_title" class="form.label"> <strong>Title:</strong></label>
                {{form.title}}
            </div>
            <div class="col">
                <label for="id_document_number" class="form.label"> <strong>Document Number:</strong></label>
                {{form.document_number}}
            </div>
<!--            <div class="col">-->
<!--                <label for="id_author" class="form.label"> <strong>Author:</strong></label>-->
<!--                {{form.author}}-->
<!--            </div>-->
            <div class="col">
                <label for="id_privacy" class="form.label"> <strong>Privacy:</strong></label>
                {{form.privacy}}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label for="id_content_type" class="form.label"> <strong>Owner Type:</strong></label>
                {{form.content_type}}
            </div>
            <div class="col">
                <label for="id_category" class="form.label"> <strong>Category:</strong></label>
                {{form.category}}
            </div>
            <div class="col">
                <label for="document_date" class="form.label"> <strong>Uploaded Date:</strong></label>
                {{form.uploaded_date}}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label for="description"> <strong>Description</strong></label>
                {{form.description}}
            </div>
<!--            <div class="col">-->
<!--                <label for="keywords"> <strong>Keywords</strong></label>-->
<!--                {{form.keywords}}-->
<!--            </div>-->
        </div>
        <div class="row class=my-3">
            <div class="col">
                <div class="col">
                    <label for="id_file" class="form.label"> <strong>File:</strong></label>
                    {{form.file}}
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end gap-3 my-3">
            <a href="{% url 'index' %}" class="btn btn-secondary d-flex-end"> <i class="bi bi-x"></i>Cancel</a>
            <button type="submit" class="btn btn-success d-flex-end"> <i class="bi bi-cloud-upload mx-2"></i>Update</button>
        </div>
    </form>

    <script>
        document.getElementById('update-document-form').onsubmit = function(event) {
            event.preventDefault(); // Prevent the default form submission

            const formData = new FormData(this);

            fetch(this.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}', // Include CSRF token
                },
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Document updated successfully!');
                    window.location.href = "{% url 'index' %}";
                } else {
                    alert('Document not updated. No changes were made.');
                    window.location.href = "{% url 'document_update' pk=pk %}";
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        };
    </script>
{% endblock %}

dms/templates/dms/index.html
{% extends 'base.html' %}

{% block title %} Index {% endblock %}
{% block contentIcon %}
    bi-files
{% endblock %}
{% block contentTitle %}
    My Files
{% endblock %}
{% block content %}
<div class="input-group mb-3">
    <span class="input-group-text">
        <i class="fas fa-search"></i>
    </span>
    <input type="text" id="search" class="form-control" placeholder="Search document..." value="{{ search_query }}" aria-label="Search document">
    <button type="button" id="clear-search" class="btn btn-secondary">Clear</button>
</div>

<p class="text-end mb-3 mx-3">
    <button type="button" onclick="uploadDocument('{% url 'document_create' %}', 'add_document', 'New document');" class="btn btn-success" data-toggle="modal" data-target="#attachmentModal">
        <i class="bi bi-file-earmark-plus"></i> New Document
    </button>
</p>

<div id="memo-results">
    {% if page_obj %}
        <div class="row table-responsive">
            <table class="table table-striped table-hover">
                <caption class="text-center">List of Documents</caption>
                <thead class="text-center">
                    <tr>
                        <th scope="col">S.No</th>
                        <th scope="col">Doc.No.</th>
                        <th scope="col">Title</th>
                        <th scope="col">Category</th>
                        <th scope="col">Doc Owner</th>
                        <th scope="col">Uploaded Date</th>
                        <th scope="col"># Actions</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider" id="document-list">
                    {% for document in page_obj %}
                    <tr class="text-center">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ document.document_number }}
                            {% if document.shared_with and request.user in document.shared_with.all %}
                                <div class="mt-1 text-danger">
                                    <i class="bi bi-toggle2-on"></i>
                                    <small class="shared-element">Shared</small>
                                </div>
                            {% endif %}
                        </td>
                        <td>{{ document.title }}</td>
                        <td>{{ document.category }}</td>
                        <td>
                            {% if document.owner %}
                                {{ document.get_owner_name }}
                            {% else %}
                                External
<!--                                Unknown Owner-->
                            {% endif %}
                        </td>
                        <td>{{ document.uploaded_date }}</td>
                        <td>
                            <a href="{% url 'document_details' pk=document.pk %}">View Details</a>
                            {% if document.shared_with and request.user in document.shared_with.all %}
                                <a class="btn btn-warning disabled" title="Edit Document" aria-disabled="true"><i class="bi bi-pencil-square"></i></a>
                                <a class="btn btn-danger disabled" title="Delete Document" aria-disabled="true"><i class="bi bi-trash3-fill"></i></a>
                            {% else %}
                                <a href="{% url 'document_update' document.id %}" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                                <a class="btn btn-hover btn-danger"
                                   href="#"
                                   data-bs-toggle="modal" data-bs-target="#confirmationModal"
                                   data-bs-action="document_delete" data-record-id="{{ document.id }}"
                                   data-modal-body-class="text-danger"
                                   data-bs-title="Delete Document" data-bs-body="Are you sure to delete document '{{ document.title }}'?">
                                    <i class="bi bi-trash3-fill"></i>
                                </a>
                            {% endif %}

                                <a href="{% url 'share_document' document.id %}"
                                   class="btn btn-info ms-2"
                                   title="Share Document"
                                   onclick="return checkDocumentPrivacy('{{ document.privacy }}');">
                                   <i class="bi bi-share"></i>
                                </a>
                        </td>
                    </tr>
                    {% empty %}
                        <tr>
                            <td colspan="7" class="text-center">No document found</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <!-- Pagination Section -->
        <div class="pagination justify-content-center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                {% endif %}

                {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                        <li class="page-item active"><span class="page-link">{{ page }}</span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                {% endif %}
            </ul>
        </div>

    {% else %}
        <h3 class="text-center">No Document found</h3>
    {% endif %}
</div>
{% include 'modal.html' %}
<!-- Include jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>

    $(document).ready(function() {
    // Existing search functionality
    $('#search').on('input', function() {
        let query = $(this).val(); // Get the current input value
        $.ajax({
            url: "{% url 'index' %}",
            data: {
                'search_query': query // Send the search query
            },
            success: function(data) {
                $('#document-list').html(data); // Update the document list
            }
        });
    });

    // Clear button functionality
    $('#clear-search').on('click', function() {
        $('#search').val(''); // Clear the search input
        $.ajax({
            url: "{% url 'index' %}", // Make a request to the index view
            success: function(data) {
                $('#document-list').html(data); // Reset the document list
            }
        });
    });

});

 function checkDocumentPrivacy(documentPrivacy) {
    // Check if the document is private
    if (documentPrivacy === 'private') {
        alert("Private document cannot be shared!"); // Alert message
        return false; // Prevent the default link action
    }
    return true; // Allow the link action if the document is not private
}
</script>

{% endblock %}